version: "3.7"

services:
    website:
        build:
            context: .
            dockerfile: Dockerfile
        image: trovster_firefox:latest
        container_name: trovster_firefox
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
        networks:
            - trovster_firefox

networks:
    trovster_firefox:
        driver: bridge

